[env:genericSTM32G431CB]
platform = ststm32
board = genericSTM32G431CB
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 9600
upload_flags =
    -c
    adapter speed 2000
board_build.mcu = stm32g431cbu6
board_build.f_cpu = 16000000L  ; Proper PIO way to set CPU freq (fixes redefinition warnings)
build_flags =
    -DSTM32G431xx
    -DHSI_VALUE=16000000UL
    -DUSE_HAL_DRIVER